### ISSUE TITLE
Flesh out README's contributing section

### ISSUE THREAD

**Issue by Jonathan-Zollinger** [Graqr/Threshr#15]
### Summary

right now the readme has only a hyperlink to the open issues. I'd like to see something more informative that also provides a snapshot of the project's outlook / progress

### Proposed Solution

I'm not sure if there's a way to use badges to dynamically show milestones and their progress? or perhaps listing open issues by type? 

### Alternative

perhaps there's a gh-actions thing we can make to update the README to reflect issues and milestones dynamically

### Additional Context

I know there are variations of progress bars that github's markdown supports. that might be of use.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)

#### Todo
- [ ] README has a more informative overview of milestones
- [ ] hyperlinks or infographics have dynamic links to appropriate content
- [ ] progress (progress bars or whatever) is made in the README w/o editing the README

**Comment by Jonathan-Zollinger** [comment]
could use something like https://shields.io/badges/git-hub-milestone-details
